heat_template_version: 2016-10-14
description: A load-balancer server
parameters:
  pool_id:
    type: string
    description: Pool to contact
  stack_id:
    type: string
    description: Stack id
resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: "m1.nano"
      image: "cirros"
      networks:
        - network: "vxlan"
      metadata: {"metering.server_group": {get_param: stack_id}}
  member:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: {get_param: pool_id}
      address: { get_attr: [ server, first_address ]}
      protocol_port: 22
      subnet: "vxlan"

outputs:
  server_ip:
    description: IP Address of the load-balanced server.
    value: { get_attr: [server, first_address] }
  lb_member:
    description: LB member details.
    value: { get_attr: [member, show] }